/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/colors`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Chat`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Notes`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NotesCard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SeedCard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Seeds`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Chat`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Notes`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/NotesCard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SeedCard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Seeds`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/colors${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/theme${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/Chat${`?${string}` | `#${string}` | ''}` | `/screens/Home${`?${string}` | `#${string}` | ''}` | `/screens/Login${`?${string}` | `#${string}` | ''}` | `/screens/Notes${`?${string}` | `#${string}` | ''}` | `/screens/NotesCard${`?${string}` | `#${string}` | ''}` | `/screens/SeedCard${`?${string}` | `#${string}` | ''}` | `/screens/Seeds${`?${string}` | `#${string}` | ''}` | `/screens/SignUp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/colors`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Chat`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Notes`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NotesCard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SeedCard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Seeds`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUp`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
